version: "1.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      ALIVE_NAME: $ALIVE_NAME
      BOT_TOKEN: $BOT_TOKEN 
      ASSISTANT_ID: $ASSISTANT_ID
      SESSION_NAME: $SESSION_NAME 
      SUPPORT: $SUPPORT
      CHANNEL: $CHANNEL
      BOT_USERNAME: $BOT_USERNAME 
      START_PIC: $START_PIC
      COMMAND_PREFIXES: $COMMAND_PREFIXES
      
