version: "1.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      ALIVE_NAME: $ALIVE_NAME
      BOT_TOKEN: $BOT_TOKEN
      
      ASSISTANT_ID: $ASSISTANT_ID
      SUDO_USERS: $SUDO_USERS
      SESSION_NAME: $SESSION_NAME
      DURATION_LIMIT: $DURATION_LIMIT
      GROUP_SUPPORT: $GROUP_SUPPORT
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      BOT_USERNAME: $BOT_USERNAME
      
      START_PIC: $START_PIC
      ALIVE_IMG: $ALIVE_IMG
      COMMAND_PREFIXES: $COMMAND_PREFIXES
      
